**딥러닝 3가지 분류 예제**

<hr>

(최종: 쿠팡 해지 예상 고객 예측) — 표준화 없음
<br>

표준화(평균/표준편차로 스케일링) 없이 3가지 분류 문제를 모두 실행 가능하게 구성

**공통 흐름:**

- CSV 준비/로드
- 모델 정의
- 학습
- 평가/예측

**구성:**

- 예제 1: 이진 분류(로지스틱) — 입력 1개(단일 컬럼)
- 예제 2: 다중 클래스 분류(3클래스) — 입력 2개(2컬럼)
- 최종: 쿠팡 해지(Churn) 이진 분류(MLP) — 입력 6개

In [ ]:
# =========================
# 0) 환경 준비
# =========================
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

np.random.seed(42)
torch.manual_seed(42)

print("torch:", torch.__version__)

torch: 2.9.0+cu126


**예제-1) 이진 분류(입력 1개): 앱 이용점수로 “구독 유지/해지 위험” 분류**
<hr>

📰
**문제**
<br>
1. CSV(app_subscribe.csv)에는 이용점수(engagement_score) 와 구독 유지 여부(subscribe=1/0) 가 있습니다.
2. PyTorch로 가장 단순한 로지스틱 분류(Linear 1→1) 를 학습하고, 점수 35/75의 구독 확률을 예측하세요.

- 입력: engagement_score (1개)
- 라벨: subscribe (0/1)
- 손실: BCEWithLogitsLoss
- 평가지표: Accuracy(0.5 threshold)

In [ ]:
# # 1) CSV 생성
# csv_text = """engagement_score,subscribe
# 10,0
# 15,0
# 20,0
# 25,0
# 30,0
# 35,0
# 40,1
# 50,1
# 60,1
# 70,1
# 80,1
# 90,1
# """
# with open("app_subscribe.csv", "w", encoding="utf-8") as f:
#     f.write(csv_text)

In [ ]:
df = pd.read_csv("app_subscribe.csv")
X = torch.tensor(df[["engagement_score"]].values, dtype=torch.float32)  # (N,1)
y = torch.tensor(df[["subscribe"]].values, dtype=torch.float32)         # (N,1)

In [ ]:
# 모델 선정
model = nn.Linear(1, 1)
# 층을 여러개 쌓았으면 활성화함수 사용해야함.

# model = nn.Sequential(
#     nn.Linear(1, 16),
#     nn.ReLU(),
#     nn.Linear(16, 8),
#     nn.ReLU(),
#     nn.Linear(8, 4),
#     nn.ReLU(),
#     nn.Linear(4, 1)
# )

In [ ]:
# 손실함수 선정
loss_fn = nn.BCEWithLogitsLoss() # 이진분류용 손실함수


In [ ]:
# 옵티마이저 선정
opt = torch.optim.SGD(model.parameters(), lr=0.001)


In [ ]:
# 분류일 때 출력 부분에 활성화함수가 필요함.
# 이진분류 - 시그모이드
# 다중분류 - 소프트맥스

In [ ]:
# 훈련시키자.
for epoch in range(6000):
  logits = model(X)
  loss = loss_fn(logits, y)

  opt.zero_grad()
  loss.backward()
  opt.step()

In [ ]:
# 예측해보자.
with torch.no_grad():
  # 출력결과를 만들 때 원하는 0,1을 얻어내기 위한 활성화함수가 필요함.
  prob = torch.sigmoid(model(X))
  print(prob)
  pred = (prob >= 0.5).float()
  print(pred)
  acc = (pred == y).float().mean().item()
  print(acc)

tensor([[0.4721],
        [0.5049],
        [0.5376],
        [0.5700],
        [0.6018],
        [0.6328],
        [0.6628],
        [0.7187],
        [0.7686],
        [0.8120],
        [0.8488],
        [0.8795]])
tensor([[0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])
0.5833333134651184


In [ ]:
# 검증해보자.
print("Train ACC:", acc)

Train ACC: 0.5833333134651184


**예제 2) 다중 클래스 분류(3클래스, 입력 2개): 날씨로 옷차림 추천 분류**
<hr>

**문제** <br>
1. CSV(outfit_weather.csv)에는 기온(temp_c) 과 풍속(wind_mps) 로부터 옷차림 클래스를 예측하는 데이터가 있습니다.

2. 라벨 outfit_class
- 0: 얇게(반팔/얇은 겉옷)
- 1: 보통(긴팔/가벼운 아우터)
- 2: 두껍게(패딩/두꺼운 옷)

<hr>

PyTorch로 3클래스 분류 모델을 학습하고, 아래 입력의 클래스를 예측하세요.


📕 예측 입력값
```
(temp=22, wind=2)
(temp=8, wind=5)
(temp=15, wind=3)
다중 분류는 CrossEntropyLoss를 사용하며, 라벨은 정수(0,1,2) 여야 합니다.

```



In [ ]:
# 1) CSV 생성
# csv_text = """temp_c,wind_mps,outfit_class
# 28,1,0
# 26,2,0
# 24,3,0
# 22,1,0
# 21,3,1
# 20,4,1
# 18,2,1
# 17,4,1
# 16,3,1
# 14,2,1
# 13,4,2
# 12,5,2
# 10,3,2
# 9,4,2
# 7,6,2
# """
# with open("outfit_weather.csv", "w", encoding="utf-8") as f:
#     f.write(csv_text)

In [ ]:
df = pd.read_csv("outfit_weather.csv")
X = torch.tensor(df[["temp_c", "wind_mps"]].values, dtype=torch.float32)# (N,2)
y = torch.tensor(df["outfit_class"].values, dtype=torch.long)    # (N,) 0/1/2

In [ ]:
df.head()

temp_c  wind_mps  outfit_class
0      28         1             0
1      26         2             0
2      24         3             0
3      22         1             0
4      21         3             1

In [ ]:
# 모델 선정
model2 = nn.Linear(2, 3) ## 3은 분류일 때, 클래스개수를 의미함. 다중분류용 손실함수를 사용하는 경우, 클래스별 확률을 가지고 손실을 계산하므로 클래스 개수만큼 넣어주어야함.
## 이진 분류에서 CrossEntropyLoss()를 쓰는 경우 2로 써주어야함.
## 이진 분류용 BCEWithLogitsLoss()를 쓰는 경우 1로 써주어야함.
## 내부적인 계산방식의 차이때문임.
# 층을 여러개 쌓았으면 활성화함수 사용해야함.

In [ ]:
# 손실함수 선정
loss_fn = nn.CrossEntropyLoss() # 다중분류용 손실함수

In [ ]:
# 옵티마이저 선정
opt = torch.optim.SGD(model2.parameters(), lr=0.05)

In [ ]:
# 학습시키고
for epoch in range(1000):
  logits = model2(X)
  loss = loss_fn(logits, y)

  opt.zero_grad()
  loss.backward()
  opt.step()

In [ ]:
# 예측하고
with torch.no_grad():
  logits = model2(X)
  print(logits[:2])
  pred = logits.argmax(dim=1)
  print(pred)
  acc = (pred == y).float().mean().item()
  print(acc)

tensor([[ 14.4444,   7.6095, -17.0992],
        [  9.8514,   7.6673, -11.4121]])
tensor([0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
0.9333333373069763


In [ ]:
## 예측을 하고 싶은데, 온도, 바람을 넣어 옷두께를 예측(판단)해보자.
## 무조건 2차원 텐서로 만들어주어야함.
test = torch.tensor([[4, 2]], dtype=torch.float32)

## 예측해보자.
with torch.no_grad():
  result = model2(test)
  print(result)
  label = torch.argmax(result)
  print(label.item())

tensor([[-4.9775,  2.1756,  6.0866]])
2


**최종 문제) 딥러닝 - 쿠팡 해지 예상 고객(Churn) 이진 분류**

<hr>

# 1. 문제 설명
쿠팡(또는 구독/커머스 서비스)에서 향후 30일 내 <b><u>해지(1) / 유지(0) </u></b> 를 예측한다고 가정합니다.

# 2. CSV(coupang_churn.csv) 컬럼:

- 입력(독립변수)
  - tenure_months : 가입 후 경과 개월
  - orders_30d : 최근 30일 주문 수
  - avg_spend : 최근 30일 평균 결제금액(가상 단위)
  - cancel_rate : 최근 취소 비율(0~1)
  - cs_tickets_30d : 최근 30일 고객센터 문의 수
  - discount_use_rate : 할인/쿠폰 사용 비율(0~1)
- 라벨(종속변수)
  - churn_30d : 30일 내 해지 여부(0/1)

In [ ]:
# =========================
# 1) CSV 생성(실습용) - 실무라면 실데이터로 교체
# =========================
np.random.seed(42)

N = 500
tenure = np.random.randint(1, 60, size=N)
orders = np.random.poisson(lam=6, size=N).clip(0, 30)
avg_spend = (np.random.normal(40, 15, size=N)).clip(5, 120)
cancel_rate = np.random.beta(a=2, b=8, size=N)
cs = np.random.poisson(lam=1.2, size=N).clip(0, 10)
discount = np.random.beta(a=2.5, b=4, size=N)

# 해지 확률 설계(학습 가능하도록 단순 구조)
logit = (
    -0.03 * tenure
    -0.10 * orders
    -0.01 * avg_spend
    + 2.8  * cancel_rate
    + 0.30 * cs
    + 1.3  * discount
    - 0.1
)
prob = 1 / (1 + np.exp(-logit))
churn = (np.random.rand(N) < prob).astype(int)

df = pd.DataFrame({
    "customer_id": np.arange(1, N+1),
    "tenure_months": tenure,
    "orders_30d": orders,
    "avg_spend": np.round(avg_spend, 2),
    "cancel_rate": np.round(cancel_rate, 4),
    "cs_tickets_30d": cs,
    "discount_use_rate": np.round(discount, 4),
    "churn_30d": churn
})
df.to_csv("coupang_churn.csv", index=False, encoding="utf-8")
df.head()

customer_id  tenure_months  orders_30d  avg_spend  cancel_rate  \
0            1             39           2      32.97       0.2906   
1            2             52           4      22.68       0.1561   
2            3             29           3      23.57       0.1974   
3            4             15           5      44.48       0.3113   
4            5             43           9      39.17       0.1083   

   cs_tickets_30d  discount_use_rate  churn_30d  
0               2             0.2307          1  
1               0             0.2693          1  
2               2             0.4031          0  
3               2             0.4955          1  
4               3             0.4507          0