In [137]:
import torch
import torch.nn as nn

# 1) 재현성
torch.manual_seed(42)

In [138]:
# 2) 예시 데이터 (면적m^2 -> 집값)
#    실제로는 CSV에서 가져오면 되지만, "가장 간단" 버전이라 여기선 직접 만듦
x = torch.tensor([[20.0],
                  [30.0],
                  [40.0],
                  [50.0],
                  [60.0]], dtype=torch.float32)   # (N, 1)

y = torch.tensor([[200.0],
                  [300.0],
                  [410.0],
                  [520.0],
                  [610.0]], dtype=torch.float32)  # (N, 1)  (예: 단위=만원/백만원 등)

In [139]:
model = nn.Linear(1, 1) # 선형회귀

In [140]:
loss_fn = nn.MSELoss()
opt = torch.optim.SGD(model.parameters(), lr=0.0001)

In [141]:
for epoch in range(3000):
    pred = model(x)
    loss = loss_fn(pred, y)

    opt.zero_grad()
    loss.backward()
    opt.step()

In [142]:
with torch.no_grad():
  new_x = torch.tensor([[45.0]], dtype=torch.float32)
  new_pred = model(new_x)

In [143]:
new_pred

tensor([[459.9994]])

In [144]:
print("가중치들 프린트>> ", model.weight.item())

가중치들 프린트>>  10.212055206298828


In [145]:
print("바이어스 프린트>> ", model.bias.item())

바이어스 프린트>>  0.4569530785083771


#### 문제
# 문제

# 아래는 집의 **면적(area, m²)**과 **방 개수(rooms)**를 이용해 **집값(price)**을 예측하는 회귀 문제입니다.

# 데이터(학습용)

# 독립변수 2개: area, rooms

# 종속변수 1개: price

# area	rooms	price
# 30	1	260
# 40	2	390
# 50	2	450
# 60	3	580
# 70	3	650
# 80	4	780



In [146]:
# PyTorch로 선형회귀 모델을 만들어 위 데이터를 학습하세요.

# 학습 후 아래 입력에 대한 가격을 예측하세요.

# (area=55, rooms=2)
# (area=75, rooms=4)

In [147]:
import torch
import torch.nn as nn
torch.manual_seed(42)

In [148]:
# 1) 데이터: (N, 2)
X = torch.tensor([
    [30.0, 1.0],
    [40.0, 2.0],
    [50.0, 2.0],
    [60.0, 3.0],
    [70.0, 3.0],
    [80.0, 4.0],
], dtype=torch.float32)

# 정답: (N, 1)
y = torch.tensor([
    [260.0],
    [390.0],
    [450.0],
    [580.0],
    [650.0],
    [780.0],
], dtype=torch.float32)

In [149]:
model = nn.Linear(2, 1)

In [150]:
loss_fn = nn.MSELoss()
opt = torch.optim.SGD(model.parameters(), lr=0.0001)

In [151]:
for epoch in range(20000):
    pred = model(X)
    loss = loss_fn(pred, y)

    opt.zero_grad()
    loss.backward()
    opt.step()


In [152]:
with torch.no_grad():
    test = torch.tensor([
        [55.0, 2.0],
        [75.0, 4.0],
    ], dtype=torch.float32)
    out = model(test)

In [153]:
print("W:", model.weight.data)  # (1,2)
print("b:", model.bias.data)    # (1,)
print("예측값:\n", out)

W: tensor([[ 8.8014, 17.6319]])
b: tensor([-8.3880])
예측값:
 tensor([[510.9518],
        [722.2432]])


In [154]:
import pandas as pd
import torch
import torch.nn as nn

In [155]:
# csv_text = """distance_km,orders,delivery_min
# 1,1,18
# 2,1,22
# 2,2,26
# 3,2,30
# 4,2,34
# 4,3,38
# 5,3,42
# 6,3,47
# 6,4,52
# 7,4,56
# """
# with open("delivery_time.csv", "w", encoding="utf-8") as f:
#     f.write(csv_text)

In [156]:
df = pd.read_csv("delivery_time.csv")
df

distance_km  orders  delivery_min
0            1       1            18
1            2       1            22
2            2       2            26
3            3       2            30
4            4       2            34
5            4       3            38
6            5       3            42
7            6       3            47
8            6       4            52
9            7       4            56

In [157]:
df.columns

Index(['distance_km', 'orders', 'delivery_min'], dtype='object')

In [158]:
X = df[['distance_km', 'orders']]
X

distance_km  orders
0            1       1
1            2       1
2            2       2
3            3       2
4            4       2
5            4       3
6            5       3
7            6       3
8            6       4
9            7       4

In [159]:
X.dtypes

distance_km    int64
orders         int64
dtype: object

In [160]:
X.values

array([[1, 1],
       [2, 1],
       [2, 2],
       [3, 2],
       [4, 2],
       [4, 3],
       [5, 3],
       [6, 3],
       [6, 4],
       [7, 4]])

In [161]:
df[['distance_km', 'orders']].values
# 이차원리스트를 이차원텐서로 만들어주어야함.

array([[1, 1],
       [2, 1],
       [2, 2],
       [3, 2],
       [4, 2],
       [4, 3],
       [5, 3],
       [6, 3],
       [6, 4],
       [7, 4]])

In [162]:
torch.tensor(df[['distance_km', 'orders']].values) #아직 정수

tensor([[1, 1],
        [2, 1],
        [2, 2],
        [3, 2],
        [4, 2],
        [4, 3],
        [5, 3],
        [6, 3],
        [6, 4],
        [7, 4]])

In [163]:
X = torch.tensor(df[['distance_km', 'orders']].values, dtype=torch.float32)
X

tensor([[1., 1.],
        [2., 1.],
        [2., 2.],
        [3., 2.],
        [4., 2.],
        [4., 3.],
        [5., 3.],
        [6., 3.],
        [6., 4.],
        [7., 4.]])

In [164]:
y = torch.tensor(df[['delivery_min']].values, dtype=torch.float32)
y

tensor([[18.],
        [22.],
        [26.],
        [30.],
        [34.],
        [38.],
        [42.],
        [47.],
        [52.],
        [56.]])

In [165]:
#### 1. 사용할 모델 선정 --> 실제에는 입력층+은닉층+출력층
model = nn.Linear(2, 1)

In [166]:
#### 2. 손실함수 + 옵티마이저를 선정
## 회귀 --> MSE
loss_fn = nn.MSELoss()
loss_fn2 = nn.L1Loss() #MAE
## SGD, Adam
opt = torch.optim.SGD(model.parameters(), lr=0.005)

In [167]:
from tqdm import tqdm

In [168]:
### 3. 학습하자. --> epoch(주기)
for epoch in tqdm(range(5000)):
    pred = model(X)
    loss = loss_fn(pred, y)
    loss2 = loss_fn2(pred, y)
    opt.zero_grad()
    loss.backward()
    opt.step()

100%|██████████| 5000/5000 [00:02<00:00, 2156.65it/s]


In [169]:
### 4. 예측하자.
with torch.no_grad():
    # 예측할 데이터를 2차원 텐서로 만들어줌.
    test = torch.tensor([[3.5, 2.0], [6.5, 4.0]], dtype=torch.float32)
    out = model(test)

In [170]:
out

tensor([[32.2399],
        [53.4267]])

In [171]:
print("3.5, 2.0 >> ", out[0])

3.5, 2.0 >>  tensor([32.2399])


In [172]:
print("3.5, 2.0 >> ", out[0].item()) #item() --> 텐서객체 내에있는 값을 추출할 때

3.5, 2.0 >>  32.2398567199707


In [173]:
print("6.5, 4.0 >> ", out[1].item())

6.5, 4.0 >>  53.42674255371094


In [174]:
### 5. 검증

In [175]:
print("mse >> " , loss)
print("mae >> " , loss2)

mse >>  tensor(0.2335, grad_fn=<MseLossBackward0>)
mae >>  tensor(0.4018, grad_fn=<MeanBackward0>)


In [176]:
### 4. 예측하자.
with torch.no_grad():
    # 예측할 데이터를 2차원 텐서로 만들어줌.
    test = torch.tensor([[3.5, 6.0], [12.5, 8.0]], dtype=torch.float32)
    out = model(test)

In [177]:
print(out)

tensor([[49.6820],
        [95.8005]])


In [178]:
model2 = nn.Sequential(
    nn.Linear(2, 16),   # 입력층
    nn.ReLU(),

    nn.Linear(16, 8),   # 히든층 2
    nn.ReLU(),

    nn.Linear(8, 1)     # 출력층
)

In [179]:
loss_fn3 = nn.MSELoss()

In [180]:
opt2 = torch.optim.Adam(model2.parameters(), lr=0.01)

In [181]:
for epoch in range(3000):
    pred = model2(X)
    loss3 = loss_fn3(pred, y)

    opt2.zero_grad()
    loss3.backward()
    opt2.step()

In [182]:
with torch.no_grad():
  test2 = torch.tensor([[3.5, 2.0], [6.5, 4.0]], dtype=torch.float32)
  out2 = model2(test2)

In [183]:
out2

tensor([[24.6215],
        [24.6215]])

In [184]:
model3 = nn.Sequential(
    nn.Linear(2, 16),   # 입력층
    nn.ReLU(),

    nn.Linear(16, 8),  # 히든층 1
    nn.ReLU(),

    nn.Linear(8, 4),   # 히든층 2
    nn.ReLU(),

    nn.Linear(4, 1)     # 출력층
)

In [185]:
opt3 = torch.optim.SGD(model3.parameters(), lr=0.0001)
loss_fn3 = nn.MSELoss()

In [186]:
for epoch in range(3000):
    pred = model3(X)
    loss3 = loss_fn3(pred, y)

    opt3.zero_grad()
    loss3.backward()
    opt3.step()

In [187]:
with torch.no_grad():
  test2 = torch.tensor([[3.5, 2.0], [6.5, 4.0]], dtype=torch.float32)
  out3 = model3(test2)

In [188]:
out3

tensor([[16.6324],
        [16.6312]])

In [189]:
# month_id,set_temp_c,outside_temp_c,occupants,monthly_kwh
# 1,23,32.9,4,486
# 2,26,-1.2,5,858
# 3,18,31.4,2,492
# 4,19,4.6,5,578
# 5,24,-2.6,5,861
# 6,28,18.3,1,356
# 7,27,18.4,1,331
# 8,20,6.6,2,423
# 9,26,-0.3,3,724
# 10,24,17.9,4,398
# 11,23,12.1,2,384
# 12,23,33.6,6,612
# 13,18,29.5,3,553
# 14,25,17.5,4,409
# 15,20,-0.8,6,716
# 16,18,13.0,4,444
# 17,27,-1.6,5,846
# 18,21,19.4,2,304
# 19,21,3.5,1,283
# 20,20,17.1,1,274
# 21,24,4.9,2,458
# 22,24,10.5,5,521
# 23,22,26.6,6,696
# 24,20,11.9,3,287
# 25,24,30.5,3,387
# 26,20,19.4,4,329
# 27,18,3.7,3,487
# 28,22,5.6,2,397
# 29,22,28.4,1,351
# 30,25,20.5,6,536
# 31,22,14.2,3,444
# 32,20,28.0,4,500
# 33,22,-0.1,1,350
# 34,20,1.5,5,634
# 35,18,24.0,4,575
# 36,27,9.8,3,523
# 37,26,31.0,5,626
# 38,19,5.7,1,286
# 39,27,13.9,3,451
# 40,25,6.5,2,420
# 41,21,31.0,2,350
# 42,23,10.2,4,504
# 43,22,6.6,2,390
# 44,23,0.3,6,732
# 45,28,19.9,1,284
# 46,25,2.2,1,338
# 47,19,22.3,4,479
# 48,22,34.5,5,565
# 49,24,6.7,4,550
# 50,23,7.6,3,433
# 51,19,8.8,6,721
# 52,18,10.1,2,356
# 53,18,18.1,5,490
# 54,23,18.1,2,349
# 55,21,9.7,2,387
# 56,18,26.6,4,474
# 57,22,2.7,5,697
# 58,23,33.2,3,447
# 59,19,3.8,2,437
# 60,25,20.0,5,429


# “전기요금(월간 전력 사용량) 예측”
**문제 상황**

가정이나 소형 사무실에서 다음 달 전기요금이 얼마나 나올지 미리 예측하고 싶습니다.
과거 사용 패턴과 생활 조건을 입력하면, 딥러닝 회귀 모델이 월간 전력 사용량(kWh) 을 예측합니다.

- 독립변수(입력 X) 3개

평균 실내 설정 온도(°C) : 냉난방(에어컨/보일러) 사용 강도를 간접적으로 반영

월 평균 외부 기온(°C) : 날씨가 덥거나 추우면 냉난방 사용 증가 가능

거주/사용 인원 수(명) : 조명, 가전, 온수, 전자기기 사용량이 인원에 따라 증가

- 종속변수(출력 y) 1개

월간 전력 사용량(kWh) (또는 직접 전기요금(원)으로 해도 됨)

In [190]:
csv_text = """month_id,set_temp_c,outside_temp_c,occupants,monthly_kwh
1,23,32.9,4,486
2,26,-1.2,5,858
3,18,31.4,2,492
4,19,4.6,5,578
5,24,-2.6,5,861
6,28,18.3,1,356
7,27,18.4,1,331
8,20,6.6,2,423
9,26,-0.3,3,724
10,24,17.9,4,398
11,23,12.1,2,384
12,23,33.6,6,612
13,18,29.5,3,553
14,25,17.5,4,409
15,20,-0.8,6,716
16,18,13.0,4,444
17,27,-1.6,5,846
18,21,19.4,2,304
19,21,3.5,1,283
20,20,17.1,1,274
21,24,4.9,2,458
22,24,10.5,5,521
23,22,26.6,6,696
24,20,11.9,3,287
25,24,30.5,3,387
26,20,19.4,4,329
27,18,3.7,3,487
28,22,5.6,2,397
29,22,28.4,1,351
30,25,20.5,6,536
31,22,14.2,3,444
32,20,28.0,4,500
33,22,-0.1,1,350
34,20,1.5,5,634
35,18,24.0,4,575
36,27,9.8,3,523
37,26,31.0,5,626
38,19,5.7,1,286
39,27,13.9,3,451
40,25,6.5,2,420
41,21,31.0,2,350
42,23,10.2,4,504
43,22,6.6,2,390
44,23,0.3,6,732
45,28,19.9,1,284
46,25,2.2,1,338
47,19,22.3,4,479
48,22,34.5,5,565
49,24,6.7,4,550
50,23,7.6,3,433
51,19,8.8,6,721
52,18,10.1,2,356
53,18,18.1,5,490
54,23,18.1,2,349
55,21,9.7,2,387
56,18,26.6,4,474
57,22,2.7,5,697
58,23,33.2,3,447
59,19,3.8,2,437
60,25,20.0,5,429
"""

with open("electricity_usage_sample.csv", "w", encoding="utf-8") as f:
    f.write(csv_text)

In [191]:
torch.manual_seed(42)

In [192]:
df2 = pd.read_csv("electricity_usage_sample.csv")
df2

month_id  set_temp_c  outside_temp_c  occupants  monthly_kwh
0          1          23            32.9          4          486
1          2          26            -1.2          5          858
2          3          18            31.4          2          492
3          4          19             4.6          5          578
4          5          24            -2.6          5          861
5          6          28            18.3          1          356
6          7          27            18.4          1          331
7          8          20             6.6          2          423
8          9          26            -0.3          3          724
9         10          24            17.9          4          398
10        11          23            12.1          2          384
11        12          23            33.6          6          612
12        13          18            29.5          3          553
13        14          25            17.5          4          409
14        15          20            -0.8          6          716
15        16          18            13.0          4          444
16        17          27            -1.6          5          846
17        18          21            19.4          2          304
18        19          21             3.5          1          283
19        20          20            17.1          1          274
20        21          24             4.9          2          458
21        22          24            10.5          5          521
22        23          22            26.6          6          696
23        24          20            11.9          3          287
24        25          24            30.5          3          387
25        26          20            19.4          4          329
26        27          18             3.7          3          487
27        28          22             5.6          2          397
28        29          22            28.4          1          351
29        30          25            20.5          6          536
30        31          22            14.2          3          444
31        32          20            28.0          4          500
32        33          22            -0.1          1          350
33        34          20             1.5          5          634
34        35          18            24.0          4          575
35        36          27             9.8          3          523
36        37          26            31.0          5          626
37        38          19             5.7          1          286
38        39          27            13.9          3          451
39        40          25             6.5          2          420
40        41          21            31.0          2          350
41        42          23            10.2          4          504
42        43          22             6.6          2          390
43        44          23             0.3          6          732
44        45          28            19.9          1          284
45        46          25             2.2          1          338
46        47          19            22.3          4          479
47        48          22            34.5          5          565
48        49          24             6.7          4          550
49        50          23             7.6          3          433
50        51          19             8.8          6          721
51        52          18            10.1          2          356
52        53          18            18.1          5          490
53        54          23            18.1          2          349
54        55          21             9.7          2          387
55        56          18            26.6          4          474
56        57          22             2.7          5          697
57        58          23            33.2          3          447
58        59          19             3.8          2          437
59        60          25            20.0          5          429

In [193]:
model3 = nn.Sequential(
    nn.Linear(3, 1666),   # 입력층
    nn.ReLU(),

    nn.Linear(1666, 1000),   # 히든층
    nn.ReLU(),

    nn.Linear(1000, 500),   # 히든층
    nn.ReLU(),

    nn.Linear(500, 100),   # 히든층
    nn.ReLU(),


    nn.Linear(100, 30),   # 히든층
    nn.ReLU(),

    nn.Linear(30, 1)     # 출력층
)

In [194]:
df2.columns

Index(['month_id', 'set_temp_c', 'outside_temp_c', 'occupants', 'monthly_kwh'], dtype='object')

In [195]:
X = torch.tensor(df2[['set_temp_c','outside_temp_c','occupants']].values, dtype=torch.float32)
# X

In [196]:
y = torch.tensor(df2[['monthly_kwh']].values, dtype=torch.float32)
# y

In [197]:
y[:5]

tensor([[486.],
        [858.],
        [492.],
        [578.],
        [861.]])

In [198]:
loss_fn4 = nn.MSELoss()
## SGD, Adam
opt4 = torch.optim.Adam(model3.parameters())

In [199]:
for epoch in tqdm(range(3000)):
    pred = model3(X)
    loss3 = loss_fn4(pred, y)

    opt4.zero_grad()
    loss3.backward()
    opt4.step()

100%|██████████| 3000/3000 [02:42<00:00, 18.41it/s]


In [200]:
with torch.no_grad():
  test4 = torch.tensor([[25,20.0,5]], dtype=torch.float32)
  out4 = model3(test4)

In [201]:
out4

tensor([[429.3564]])

In [202]:
loss3

tensor(276.6176, grad_fn=<MseLossBackward0>)